TASEF/TASEF/Controllers/FluxTresorerieMAParametersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using TASEF.Infrastructure;
using TASEF.Models;

namespace TASEF.Controllers
{
    public class FluxTresorerieMAParametersController : Controller
    {


        private ExcelProjectContext db = new ExcelProjectContext();

        // GET: Parameters
        [Authorize]
        public ActionResult Index()
        {
            if (Session["SteInformation"] == null)
            {
                ViewBag.Error = "Vous devez d'abord choisir une entreprise ! <a href=\"/Home/Index\"> Tous les entreprises </a>";
                return View("FileError");
            }
            else if (Session["firstInputFile"] == null || Session["secondInputFile"] == null)
            {
                ViewBag.Error = "Vous devez d'abord importer les fichiers ! <a href=\"/Excel/Input\"> Importer </a>";
                return View("FileError");
            }

            generalSettings gs = (generalSettings)Session["SteInformation"];

            var ParamSetting = from ps in db.ParametersSetting
                               where ps.ownerId.Equals(gs.ownerId) && ps.matricule.Equals(gs.matricule) && ps.exercice == gs.exercice
                               select ps;

            ParametersSetting paramFluxMA = ParamSetting.FirstOrDefault();
            if (!paramFluxMA.hasParamFluxMA)
                return View("ParamSetting");
            else
            {

                IEnumerable<ExcelInfo> firstInputFile = (IEnumerable<ExcelInfo>)Session["firstInputFile"];
                IEnumerable<ExcelInfo> secondInputFile = (IEnumerable<ExcelInfo>)Session["secondInputFile"];

                IEnumerable<ExcelInfo> InputFile = firstInputFile.Concat(secondInputFile);

                //calculate the values foreach parameter
                int exercice = gs.exercice;
                string matricule = gs.matricule;
                string ownerId = gs.ownerId;

                var af = from a in db.FluxTresorerieMAModel
                         where a.exercice == exercice && a.matricule.Equals(matricule) && a.ownerId.Equals(ownerId)
                         select a;

                var databaseFormulaList = from fl in db.FluxTresorerieMAFormula
                                          where fl.exercice == exercice && fl.matricule.Equals(matricule) && fl.ownerId.Equals(ownerId)
                                          select fl;


                //there are no FluxTresorerieMA parameters for that company so we need to create them
                if (!af.Any())
                {
                    List<FluxTresorerieMAParamModel> FluxTresorerieMAParamList = new List<FluxTresorerieMAParamModel>
            {
                new FluxTresorerieMAParamModel(){ code="0001" , libelle ="Flux de Trésorerie provenant de (affectés à) l'Exploitation" , type="Formula",state="Stable",priority=0},
                new FluxTresorerieMAParamModel(){ code="0002" , libelle ="Résultat net" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0003" , libelle ="Ajustement amortissement et provision" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0004" , libelle ="variation des stocks" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0005" , libelle ="Variation des créances" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0006" , libelle ="Variation des autres actifs" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0007" , libelle ="Variation des fournisseurs et autres dettes" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0008" , libelle ="Ajustement plus au moins values de cession" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0009" , libelle ="Ajustement transfert des charges" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0010" , libelle ="Autres (Flux de Trésorerie provenant de (affectés à) l'Exploitation ) " , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0011" , libelle ="Flux de Trésorerie provenant de (affectés aux)  activités d'Investissement(N)" , type="Formula",state="Stable",priority=0},
                new FluxTresorerieMAParamModel(){ code="0012" , libelle ="Décaissements provenant de l'acquisition d'immobilisations corporelles et incorporelles" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0013" , libelle ="Encaissements provenant de l'acquisition d'immobilisations corporelles et incorporelles" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0014" , libelle ="Décaissements provenant de l'acquisition d'immobilisations financières" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0015" , libelle ="Encaissements provenant de l'acquisition d'immobilisations financières" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0016" , libelle ="Autres (Flux de Trésorerie provenant de (affectés aux)  activités d'Investissement) " , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0017" , libelle ="Flux de Trésorerie provenant des (affectés aux) activités de Financement " , type="Formula",state="Stable",priority=0},
                new FluxTresorerieMAParamModel(){ code="0018" , libelle ="Encaissement suite à l'émission d'actions " , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0019" , libelle ="Dividendes et autres distribution " , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0020" , libelle ="Encaissements provenant des emprunts " , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0021" , libelle ="Remboursement d'emprunts " , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0022" , libelle =" Autres (Flux de Trésorerie provenant des (affectés aux) activités de Financement) " , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0023" , libelle ="Incidences des variations des taux de change/les liquidités&équiv°(N et) " , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0024" , libelle ="Autres Postes des Flux de Trésorerie" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0025" , libelle ="Variation de Trésorerie" , type="Formula",state="Stable",priority=1},
                new FluxTresorerieMAParamModel(){ code="0026" , libelle ="Trésorerie au début de l'exercice" , type="Calculated",state="Stable"},
                new FluxTresorerieMAParamModel(){ code="0027" , libelle ="Trésorerie à la clôture de l'exercice" , type="Calculated",state="Stable"},
            };

                    foreach (var param in FluxTresorerieMAParamList)
                    {
                        var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                        var currentUser = manager.FindById(User.Identity.GetUserId());
                        param.ownerId = currentUser.Id;
                        param.exercice = exercice;
                        param.matricule = matricule;
                        param.netN = 0;
                        param.netN1 = 0;
                        db.FluxTresorerieMAModel.Add(param);
                        db.SaveChanges();
                    }
                    return View(FluxTresorerieMAParamList);

                }
                else return View(af);
            }
        }

        //GET /Parameters/Create/0001
        [Authorize]
        public ActionResult Create(string id)
        {
            List<string> definedParam = new List<string>(new string[] { "0001", "0011", "0017", "0025" });
            if (definedParam.Contains(id))
            {
                ViewBag.Error = "Ces paramétres ne peuvent pas être modifier! <a href=\"/FluxTresorerieMAParametersParameters/Index\"> Paramétres </a>";
                return View("FileError");
            }
            generalSettings gs = (generalSettings)Session["SteInformation"];
            string matricule = gs.matricule;
            int exercice = gs.exercice;
            string ownerId = gs.ownerId;


            var listFormula = from lf in db.FluxTresorerieMAFormula
                              where lf.codeParam == id
                              && lf.matricule.Equals(matricule)
                              && lf.exercice == exercice
                              && lf.ownerId.Equals(ownerId)
                              select lf;
            ViewBag.listFormula = listFormula;
            FluxTresorerieMAFormula af = new FluxTresorerieMAFormula() { codeParam = id };
            return View(af);
        }

        // POST: FluxTresorerieMAFormulas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,codeParam,codeDonnee,nomCompte,typeFormule,RANjournal")] FluxTresorerieMAFormula FluxTresorerieMAFormula)
        {
            if (ModelState.IsValid)
            {

TASEF/TASEF/Views/FluxTresorerieMAParameters/Create.cshtml
@model TASEF.Models.FluxTresorerieMAFormula

@{
                /**/

                ViewBag.Title = "Ajouter Formule";
}

<h2>Ajouter Formule</h2>
@{
    if (@ViewBag.listFormula != null)
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.codeDonnee)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.nomCompte)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.typeFormule)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RANjournal)
                </th>
                <th id="smallParameterLinks"></th>
            </tr>

            @foreach (var item in @ViewBag.listFormula)
            {
                <tr>
                    <td>
                        @item.codeDonnee
                    </td>
                    <td>
                        @item.nomCompte
                    </td>
                    <td>
                        @item.typeFormule
                    </td>
                    <td>
                        @{ if (@item.RANjournal.Equals("Tous"))
                            { @("Tous les journaux") }
                        else if (@item.RANjournal.Equals("RAN"))
                        { @("Report a nouveau") }
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Modifier", "EditFormula", new { id = item.Id }) |
                        @Html.ActionLink("Supprimer", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    } }

<button id="show" class="btn btn-default">Ajouter compte</button>

@using (Html.BeginForm("Create", "FluxTresorerieMAParameters", FormMethod.Post, new { @style = "display:none", id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Formule</h4>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.codeParam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codeParam, new { htmlAttributes = new { @class = "form-control", Value = Model.codeParam, type = "hidden" } })
                @Html.EditorFor(model => model.codeParam, new { htmlAttributes = new { @class = "form-control", Value = Model.codeParam, @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.codeParam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.codeDonnee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codeDonnee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codeDonnee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nomCompte, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomCompte, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomCompte, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.typeFormule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("typeFormule", new List<SelectListItem>
                         { new SelectListItem { Text = "Solde", Value = "Solde", Selected=true},
                           new SelectListItem { Text = "Mouvement Débiteur", Value = "MvtDebit"},
                           new SelectListItem { Text = "Mouvement Créditeur", Value = "MvtCredit"},
                           new SelectListItem { Text = "Solde Si Débiteur", Value = "SoldeSiD"},
                           new SelectListItem { Text = "Solde Si Créditeur", Value = "SoldeSiC"}
                           }, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.typeFormule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RANjournal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RANjournal", new List<SelectListItem>
                         { new SelectListItem { Text = "Tous les journaux", Value = "Tous", Selected=true},
                           new SelectListItem { Text = "journale RAN", Value = "RAN"}
                           }, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RANjournal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <br />@Html.ActionLink("Retour", "Index", null, new { id = "brownLink" })
</div>

@section Scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#hide").click(function () {
                $("form").hide();
            });
            $("#show").click(function () {
                $("form").show();
            });
        });
    </script>

}

TASEF/TASEF/Views/FluxTresorerieMAParameters/Delete.cshtml
@model TASEF.Models.FluxTresorerieMAFormula

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Confirmer la suppression!</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.codeParam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codeParam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.codeDonnee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codeDonnee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nomCompte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomCompte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typeFormule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeFormule)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour", "Index", null, new { id = "brownLink" })
        </div>
    }
</div>

TASEF/TASEF/Views/FluxTresorerieMAParameters/EditFormula.cshtml
@model TASEF.Models.FluxTresorerieMAFormula

@{
    ViewBag.Title = "Modifier formule";
}

<h2>Modification de formule</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Formule</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    @Html.HiddenFor(model => model.exercice)

    @Html.HiddenFor(model => model.matricule)

    @Html.HiddenFor(model => model.ownerId)

    <div class="form-group">
        @Html.LabelFor(model => model.codeParam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.codeParam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.codeParam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.codeDonnee, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.codeDonnee, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.codeDonnee, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nomCompte, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nomCompte, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nomCompte, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.typeFormule, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("typeFormule", new List<SelectListItem>
                            { new SelectListItem { Text = "Solde", Value = "Solde", Selected=true},
                              new SelectListItem { Text = "Mouvement Débiteur", Value = "MvtDebit"},
                              new SelectListItem { Text = "Mouvement Créditeur", Value = "MvtCredit"},
                              new SelectListItem { Text = "Solde Si Débiteur", Value = "SoldeSiD"},
                              new SelectListItem { Text = "Solde Si Créditeur", Value = "SoldeSiC"}
                              }, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.typeFormule, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RANjournal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("RANjournal", new List<SelectListItem>
                             { new SelectListItem { Text = "Tous les journaux", Value = "Tous", Selected=true},
                               new SelectListItem { Text = "journale RAN", Value = "RAN"}
                               }, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RANjournal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Enregistrer" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour", "Index", null, new { id = "brownLink" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TASEF/TASEF/Views/FluxTresorerieMAParameters/EditParam.cshtml
@model TASEF.Models.FluxTresorerieMAParamModel

@{
    ViewBag.Title = "Modifier paramétres";
}

<h2>Modification du paramétre</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Paramétre</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.code)

    @Html.HiddenFor(model => model.exercice)

    @Html.HiddenFor(model => model.matricule)

    @Html.HiddenFor(model => model.ownerId)

    @Html.HiddenFor(model => model.libelle)

    @Html.HiddenFor(model => model.type)


    <div class="form-group">
        @Html.LabelFor(model => model.netN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.netN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.netN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.netN1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.netN1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.netN1, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Enregistrer" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour", "Index", null, new { id = "brownLink" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TASEF/TASEF/Views/FluxTresorerieMAParameters/FluxTresorerieMANotesAsPdf.cshtml
@model IEnumerable<TASEF.Models.FluxTresorerieMAParamModel>
@using TASEF.Models;
@{
    ViewBag.Title = "Flux Trésorerie - Modèle Autorisé";
    Layout = "~/Views/Shared/_pdfLayout.cshtml";
    string value = "class=dd";
    generalSettings gs = (generalSettings)Session["SteInformation"];
    string exercice = gs.dateClotureExercice.ToString("dd/MM/yyyy");
    string exercice1 = gs.dateClotureExercice.AddYears(-1).ToString("dd/MM/yyyy");
}

<table class="table">
    <tr>
        <th>
            Note
        </th>
        <th>
           
        </th>
        <th>
            
        </th>
        <th>
            @exercice
        </th>
        <th>
            @exercice1
        </th>
        <th>
            Différence
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.type.Equals("Calculated"))
        {
        <tr>
            <td>
                @item.code
            </td>
            <td style="color:red">
                @Html.DisplayFor(modelItem => item.libelle)
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
            <td></td>
        </tr>

            IEnumerable<FluxTresorerieMAFormula> af = ViewBag.listFormula;
            IEnumerable<FluxTresorerieMAFormula> specificaf = af.Where(F => F.codeParam.Equals(item.code));

            foreach (FluxTresorerieMAFormula saf in specificaf)
            {
        <tr>
            <td></td>
            <td id="code">@saf.codeDonnee</td>
            <td >@saf.nomCompte</td>
            @{
                float first = 0;
                float second = 0;
                float diff;
                foreach (ExcelInfo aaf in ViewBag.firstFile)
                {
                    if (aaf.compte.StartsWith(saf.codeDonnee))
                    {
                        first += aaf.debit - aaf.credit;
                    }
                }
                foreach (ExcelInfo aaaf in ViewBag.secondFile)
                {

                    if (aaaf.compte.StartsWith(saf.codeDonnee))
                    {
                        second += aaaf.debit - aaaf.credit;
                    }
                }
            }
            <td>@first</td>
            <td>@second</td>
            @{diff = first - second;}
            <td>@diff</td>
        </tr>
            }
        }

    }

</table>

TASEF/TASEF/Views/FluxTresorerieMAParameters/FluxTresorerieMAsAsPdf.cshtml
@model IEnumerable<TASEF.Models.FluxTresorerieMAParamModel>

@{
    ViewBag.Title = "Flux Trésorerie- Modèle Autorisé";
    Layout = "~/Views/Shared/_pdfLayout.cshtml";
    string value = "class=dd";
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.libelle)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.netN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.netN1)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr @{if (item.type.Equals("Formula")) { @value  }}>
            <td>
                @Html.DisplayFor(modelItem => item.code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.libelle)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.netN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.netN1)
            </td>
        </tr>
    }

</table>

TASEF/TASEF/Views/FluxTresorerieMAParameters/GenerateFiles.cshtml
@{
    ViewBag.Title = "Fichiers";
}

<h2>Génération des fichiers</h2>
<div id="wrapper">
    <div id="centerDiv">
        @Html.ActionLink("Générer le fichier .pdf", "PrintFluxTresorerieMAsAsPdf", "FluxTresorerieMAParameters", null, new { @class = "btn btn-default" })

        @Html.ActionLink("Générer le fichier .xml", "PrintFluxTresorerieMAsAsXml", "FluxTresorerieMAParameters", null, new { @class = "btn btn-default", id = "buttonMargin" })
    </div>
</div>

TASEF/TASEF/Views/FluxTresorerieMAParameters/GenerateNoteFiles.cshtml
@{
    ViewBag.Title = "Notes";
}

<h2>Génération des notes</h2>
<div id="wrapper">
    <div id="centerDiv">
        @Html.ActionLink("Générer le fichier .pdf", "PrintFluxTresorerieMANotesAsPdf", "FluxTresorerieMAParameters", null, new { @class = "btn btn-default" })
    </div>
</div>

TASEF/TASEF/Views/FluxTresorerieMAParameters/Show.cshtml
@model IEnumerable<TASEF.Models.FluxTresorerieMAParamModel>

@{
    ViewBag.Title = "Détails paramétre";
    List<string> minus = (List<string>)ViewBag.minus;
    string value1 = "class=dd";
    string value2 = "class=gg";
}

<h2>Liste des paramétres</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.libelle)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.netN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.netN1)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr @{ if (minus.Contains(item.code)) { @value1  } else { @value2  }}>
            <td>
                @Html.DisplayFor(modelItem => item.code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.libelle)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.netN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.netN1)
            </td>
        </tr>
    }

</table>