TASEF/TASEF/Controllers/ParametersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using TASEF.Infrastructure;
using TASEF.Models;

namespace TASEF.Controllers
{
    public class ParametersController : Controller
    {
        private ExcelProjectContext db = new ExcelProjectContext();

        // GET: Parameters
        [Authorize]
        public ActionResult Index()
        {
            if (Session["SteInformation"] == null)
            {
                ViewBag.Error = "Vous devez d'abord choisir une entreprise ! <a href=\"/Home/Index\"> Tous les entreprises </a>";
                return View("FileError");
            }
            else if (Session["firstInputFile"] == null || Session["secondInputFile"] == null || Session["ExcelModelView"] == null)
            {
                ViewBag.Error = "Vous devez d'abord importer les fichiers  !  <a href=\"/Excel/Input\"> Importer </a>";
                return View("FileError");
            }

            generalSettings gs = (generalSettings)Session["SteInformation"];

            var ParamSetting = from ps in db.ParametersSetting
                               where ps.ownerId.Equals(gs.ownerId) && ps.matricule.Equals(gs.matricule) && ps.exercice == gs.exercice
                               select ps;
            ParametersSetting paramActif = ParamSetting.FirstOrDefault();

            if (!paramActif.hasParamActif)
                return View("ParamSetting");
            else
            {

                IEnumerable<ExcelInfo> firstInputFile = (IEnumerable<ExcelInfo>)Session["firstInputFile"];
                IEnumerable<ExcelInfo> secondInputFile = (IEnumerable<ExcelInfo>)Session["secondInputFile"];

                IEnumerable<ExcelInfo> InputFile = firstInputFile.Concat(secondInputFile);

                //calculate the values foreach parameter
                int exercice = gs.exercice;
                string matricule = gs.matricule;
                string ownerId = gs.ownerId;

                var af = from a in db.ActifModel
                         where a.exercice == exercice && a.matricule.Equals(matricule) && a.ownerId.Equals(ownerId)
                         select a;

                var databaseFormulaList = from fl in db.ActifFormula
                                          where fl.exercice == exercice && fl.matricule.Equals(matricule) && fl.ownerId.Equals(ownerId)
                                          select fl;


                //there are no actif parameters for that company so we need to create them
                if (!af.Any())
                {
                    List<ActifParamModel> actifParamList = new List<ActifParamModel>
            {
                new ActifParamModel(){ code="0001" , libelle ="Actifs non courants" , type="Formula",state="Stable",priority=3},
                new ActifParamModel(){ code="0002" , libelle ="Actifs immobilises" , type="Formula",state="Stable",priority=2},
                new ActifParamModel(){ code="0003" , libelle ="Immobilisations Incorporelles" , type="Formula",state="Stable",priority=1},
                new ActifParamModel(){ code="0004" , libelle ="Investissement recherche et développement" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0005" , libelle ="Concess. marque,brevet,licence,marque" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0006" , libelle ="Logiciels" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0007" , libelle ="Fonds commercial" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0008" , libelle ="Droit au bail" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0009" , libelle ="Autres Immobilisations Incorporelles" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0010" , libelle ="Immobilisations Incorporelles en cours" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0011" , libelle ="Av. et Ac.  Verses/Cmde.Immob.Incorp." , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0012" , libelle ="Immobilisations corporelles" , type="Formula",state="Stable",priority=1},
                new ActifParamModel(){ code="0013" , libelle ="Terrains" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0014" , libelle ="Constructions" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0015" , libelle ="Inst. Tech., materiel et outillages Industriels" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0016" , libelle ="Materiel de transport" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0017" , libelle ="Autres Immobilisations Corporelles" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0018" , libelle ="Immob. Corporelles en cours" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0019" , libelle ="Av. et Ac. Verses/Commande Immob.Corp." , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0020" , libelle ="Immob. a statut juridique particulier" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0021" , libelle ="Immobilisations Financieres" , type="Formula",state="Stable",priority=1},
                new ActifParamModel(){ code="0022" , libelle ="Actions" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0023" , libelle ="Autres creances rattach. a des participat." , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0024" , libelle ="Creances rattach. a des stes en participat." , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0025" , libelle ="Vers.a eff./titre de participation non liberes" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0026" , libelle ="Titres immobilises (droit de propriete)" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0027" , libelle ="Titres immobilises (droit de creance)" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0028" , libelle ="Depots et cautionnements verses" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0029" , libelle ="Autres creances immobilisees" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0030" , libelle ="Vers.a eff./Titres immobilises non liberes" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0031" , libelle ="Autres Actifs Non Courants" , type="Formula",state="Stable",priority=1},
                new ActifParamModel(){ code="0032" , libelle ="Frais preliminaires" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0033" , libelle ="Charges a repartir" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0034" , libelle ="Frais d'emission et primes de Remb. Empts" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0035" , libelle ="ecarts de conversion" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0036" , libelle ="Actifs courants" , type="Formula",state="Stable",priority=2},
                new ActifParamModel(){ code="0037" , libelle ="Stocks" , type="Formula",state="Stable",priority=1},
                new ActifParamModel(){ code="0038" , libelle ="Stocks Matieres Premieres et Fournit. Liees" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0039" , libelle ="Stocks Autres Approvisionnements" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0040" , libelle ="Stocks En-cours de production de biens" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0041" , libelle ="Stocks En-cours de production services" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0042" , libelle ="Stocks de produits" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0043" , libelle ="Stocks de marchandises" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0044" , libelle ="Clients et Comptes Rattaches" , type="Formula",state="Stable",priority=1},
                new ActifParamModel(){ code="0045" , libelle ="Clients  et  comptes rattaches" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0046" , libelle ="Clients - effets a recevoir" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0047" , libelle ="Clients douteux ou litigieux" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0048" , libelle ="Creances/travaux non encore facturables" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0049" , libelle ="Clt-pdts non encore factures (pdt a recev.)" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0050" , libelle ="Autres Actifs Courants" , type="Formula",state="Stable",priority=1},
                new ActifParamModel(){ code="0051" , libelle ="Fournisseurs debiteurs" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0052" , libelle ="Personnel et comptes rattaches" , type="Calculated",state="Stable"},
                new ActifParamModel(){ code="0053" , libelle ="etat et collectivites publiques" , type="Calculated",state="Stable"},

TASEF/TASEF/Views/Parameters/ActifNotesAsPdf.cshtml
@model IEnumerable<TASEF.Models.ActifParamModel>
@using TASEF.Models;
@{
    ViewBag.Title = "Notes - Actifs";
    Layout = "~/Views/Shared/_pdfLayout.cshtml";
    string value = "class=dd";
    generalSettings gs = (generalSettings)Session["SteInformation"];
    string exercice = gs.dateClotureExercice.ToString("dd/MM/yyyy");
    string exercice1 = gs.dateClotureExercice.AddYears(-1).ToString("dd/MM/yyyy");
}

<table class="table">
    <tr>
        <th>
            Note
        </th>
        <th>
           
        </th>
        <th>
            
        </th>
        <th>
            @exercice
        </th>
        <th>
            @exercice1
        </th>
        <th>
            Différence
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.type.Equals("Calculated"))
        {
        <tr>
            <td>
               @item.code
            </td>
            <td style="color:red">
                @Html.DisplayFor(modelItem => item.libelle)
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
            <td></td>
        </tr>

            IEnumerable<ActifFormula> af = ViewBag.listFormula;
            IEnumerable<ActifFormula> specificaf = af.Where(F => F.codeParam.Equals(item.code));

            foreach (ActifFormula saf in specificaf)
            {
        <tr>
            <td></td>
            <td id="code">@saf.codeDonnee</td>
            <td >@saf.nomCompte</td>
            @{
                float first = 0;
                float second = 0;
                float diff;
                foreach (ExcelInfo aaf in ViewBag.firstFile)
                {
                    if (aaf.compte.StartsWith(saf.codeDonnee))
                    {
                        first += aaf.debit - aaf.credit;
                    }
                }
                foreach (ExcelInfo aaaf in ViewBag.secondFile)
                {

                    if (aaaf.compte.StartsWith(saf.codeDonnee))
                    {
                        second += aaaf.debit - aaaf.credit;
                    }
                }
            }
            <td>@first</td>
            <td>@second</td>
            @{diff = first - second;}
            <td>@diff</td>
        </tr>
            }
        }

    }

</table>

TASEF/TASEF/Views/Parameters/ActifsAsPdf.cshtml
@model IEnumerable<TASEF.Models.ActifParamModel>

@{
    ViewBag.Title = "Actifs";
    Layout = "~/Views/Shared/_pdfLayout.cshtml";
    string value = "class=dd";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.libelle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.brutN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.amortProvN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.netN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.netN1)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr @{if (item.type.Equals("Formula")) { @value  }}>
            <td>
                @Html.DisplayFor(modelItem => item.code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.libelle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.brutN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.amortProvN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.netN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.netN1)
            </td>
        </tr>
    }

</table>

TASEF/TASEF/Views/Parameters/Create.cshtml
@model TASEF.Models.ActifFormula

@{
    ViewBag.Title = "Ajouter formule";
}

<h2>Ajouter formule</h2>
@{
    if (@ViewBag.listFormula != null)
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.codeDonnee)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.nomCompte)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.typeFormule)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.genre)
                </th>
                <th id="smallParameterLinks"></th>
            </tr>

            @foreach (var item in @ViewBag.listFormula)
            {
                <tr>
                    <td>
                        @item.codeDonnee
                    </td>
                    <td>
                        @item.nomCompte
                    </td>
                    <td>
                        @{ if (@item.typeFormule.Equals("Solde"))
                            {
                                @("Solde")
                            }
                            else if (@item.typeFormule.Equals("MvtDebit"))
                            { @("Mouvement Débiteur") }
                        else if (@item.typeFormule.Equals("MvtCredit"))
                        { @("Mouvement Créditeur") }
                    else if (@item.typeFormule.Equals("SoldeSiD"))
                    { @("Solde Si Débiteur") }
                else if (@item.typeFormule.Equals("SoldeSiC"))
                { @("Solde Si Créditeur") }
                        }
                    </td>
                    <td>
                        @{ if (@item.genre.Equals("Brut"))
                            {
                                @("Brut")
                            }
                            else if (@item.genre.Equals("Amor"))
                            { @("Amortissements et provisions") }
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Modifier", "EditFormula", new { id = item.Id }) |
                        @Html.ActionLink("Supprimer", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    } }

<button id="show" class="btn btn-default">Ajouter compte</button>

@using (Html.BeginForm("Create", "Parameters", FormMethod.Post, new { @style = "display:none", id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.codeParam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codeParam, new { htmlAttributes = new { @class = "form-control", Value = Model.codeParam, type = "hidden" } })
                @Html.EditorFor(model => model.codeParam, new { htmlAttributes = new { @class = "form-control", Value = Model.codeParam, @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.codeParam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.codeDonnee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codeDonnee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codeDonnee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nomCompte, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomCompte, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomCompte, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.typeFormule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("typeFormule", new List<SelectListItem>
                                 { new SelectListItem { Text = "Solde", Value = "Solde", Selected=true},
                                   new SelectListItem { Text = "Mouvement Débiteur", Value = "MvtDebit"},
                                   new SelectListItem { Text = "Mouvement Créditeur", Value = "MvtCredit"},
                                   new SelectListItem { Text = "Solde Si Débiteur", Value = "SoldeSiD"},
                                   new SelectListItem { Text = "Solde Si Créditeur", Value = "SoldeSiC"}
                                   }, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.typeFormule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("genre", new List<SelectListItem>
                                 { new SelectListItem { Text = "Brut", Value = "Brut", Selected=true},
                                   new SelectListItem { Text = "Amortissements et provisions", Value = "Amor"}
                                   }, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <br />@Html.ActionLink("Retour", "Index", null, new { id = "brownLink" })
</div>
@section Scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#hide").click(function () {
                $("form").hide();
            });
            $("#show").click(function () {
                $("form").show();
            });
        });
    </script>

}

TASEF/TASEF/Views/Parameters/Delete.cshtml
@model TASEF.Models.ActifFormula

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Confirmer la suppression!</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.codeParam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codeParam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.codeDonnee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codeDonnee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nomCompte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomCompte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typeFormule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeFormule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour", "Index", null, new { id = "brownLink" })
        </div>
    }
</div>

TASEF/TASEF/Views/Parameters/EditFormula.cshtml
@model TASEF.Models.ActifFormula

@{
    ViewBag.Title = "Modifier formule";
}

<h2>Modification de formule</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Formule</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    @Html.HiddenFor(model => model.exercice)

    @Html.HiddenFor(model => model.matricule)

    @Html.HiddenFor(model => model.ownerId)

    <div class="form-group">
        @Html.LabelFor(model => model.codeParam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.codeParam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.codeParam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.codeDonnee, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.codeDonnee, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.codeDonnee, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nomCompte, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nomCompte, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nomCompte, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.typeFormule, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("typeFormule", new List<SelectListItem>
                            { new SelectListItem { Text = "Solde", Value = "Solde", Selected=true},
                              new SelectListItem { Text = "Mouvement Débiteur", Value = "MvtDebit"},
                              new SelectListItem { Text = "Mouvement Créditeur", Value = "MvtCredit"},
                              new SelectListItem { Text = "Solde Si Débiteur", Value = "SoldeSiD"},
                              new SelectListItem { Text = "Solde Si Créditeur", Value = "SoldeSiC"}
                              }, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.typeFormule, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.genre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("genre", new List<SelectListItem>
                             { new SelectListItem { Text = "Brut", Value = "Brut", Selected=true},
                               new SelectListItem { Text = "Amortissements et provisions", Value = "Amor"}
                               }, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.genre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Enregistrer" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour", "Index", null, new { id = "brownLink" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TASEF/TASEF/Views/Parameters/EditParam.cshtml
@model TASEF.Models.ActifParamModel

@{
    ViewBag.Title = "Modifier paramétres";
}

<h2>Modification du paramétre</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Paramétre</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.code)

    @Html.HiddenFor(model => model.exercice)

    @Html.HiddenFor(model => model.matricule)

    @Html.HiddenFor(model => model.ownerId)

    @Html.HiddenFor(model => model.libelle)

    @Html.HiddenFor(model => model.type)

    <div class="form-group">
        @Html.LabelFor(model => model.brutN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.brutN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.brutN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.amortProvN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.amortProvN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.amortProvN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.netN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.netN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.netN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.netN1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.netN1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.netN1, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Enregistrer" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour", "Index",null,new { id = "brownLink"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TASEF/TASEF/Views/Parameters/GenerateFiles.cshtml
@{
    ViewBag.Title = "Fichiers";
}

<h2>Génération des fichiers</h2>
<div id="wrapper">
    <div id="centerDiv">
        @Html.ActionLink("Générer le fichier .pdf", "PrintActifsAsPdf", "Parameters", null, new { @class = "btn btn-default" })

        @Html.ActionLink("Générer le fichier .xml", "PrintActifsAsXml", "Parameters", null, new { @class = "btn btn-default", id = "buttonMargin" })
    </div>
</div>

TASEF/TASEF/Views/Parameters/GenerateNoteFiles.cshtml
@{
    ViewBag.Title = "Notes";
}

<h2>Génération des notes</h2>
<div id="wrapper">
    <div id="centerDiv">
        @Html.ActionLink("Générer le fichier .pdf", "PrintActifNotesAsPdf", "Parameters", null, new { @class = "btn btn-default" })
    </div>
</div>