TASEF/TASEF/Controllers/ExcelController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using TASEF.Infrastructure;
using TASEF.Models;
using Excel = Microsoft.Office.Interop.Excel;

namespace TASEF.Controllers
{
    public class ExcelController : Controller
    {
        private ExcelProjectContext db = new ExcelProjectContext();

        // GET: Excel
        [Authorize]
        public ActionResult Index()
        {
            Session.Clear();
            return View();
        }

        [Authorize]
        public ActionResult NewFiles(string Id)
        {
            generalSettings gs = (generalSettings)Session["SteInformation"];
            ViewBag.fps = String.Format("{0:yyyy-MM-dd}", gs.dateDebutExercice.AddYears(-1));
            ViewBag.fpe = String.Format("{0:yyyy-MM-dd}", gs.dateClotureExercice.AddYears(-1));
            ViewBag.sps = String.Format("{0:yyyy-MM-dd}", gs.dateDebutExercice);
            ViewBag.spe = String.Format("{0:yyyy-MM-dd}", gs.dateClotureExercice);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ImportNewFiles([Bind(Include = "firstPeriodStart,firstPeriodEnd,firstfile,secondPeriodStart,secondPeriodEnd,secondfile")] ExcelModelView model)
        {
            var files = HttpContext.Request.Files;
            if (files.Get(0).ContentLength == 0)
            {
                ViewBag.firstfileError = "Le fichier que vous avez impoter est vide!";
                return View("Input");
            }
            else if (files.Get(1).ContentLength == 0)
            {
                ViewBag.secondfileError = "Le fichier que vous avez impoter est vide!";
                return View("Input");
            }
            else if (model.firstPeriodStart > model.firstPeriodEnd)
            {
                @ViewBag.firstPeriodError = " La date de début et la date de clotûre de la première période doivent être en ordre!";
                return View("Input");
            }
            else if (model.secondPeriodStart > model.secondPeriodEnd)
            {
                @ViewBag.firstPeriodError = "La date de début et la date de clotûre de la deuxième période doivent être en ordre!";
                return View("Input");
            }
            else if (model.secondPeriodStart < model.firstPeriodEnd)
            {
                @ViewBag.firstPeriodError = "Les deux périodes ne doivent pas s'intercepter!";
                return View("Input");
            }
            else
            {
                if ((files.Get(0).FileName.EndsWith("xls") || files.Get(0).FileName.EndsWith("xlsx")) && (files.Get(1).FileName.EndsWith("xls") || files.Get(1).FileName.EndsWith("xlsx")))
                {
                    //saving the file
                    #region Unique File Name Generation

                    string finaldate = DateTime.Now.ToString("_MMddyyyy_HHmmss");

                    string firstname = Path.GetFileNameWithoutExtension(files.Get(0).FileName);
                    string firstext = Path.GetExtension(files.Get(0).FileName);
                    string secondname = Path.GetFileNameWithoutExtension(files.Get(1).FileName);
                    string secondext = Path.GetExtension(files.Get(1).FileName);
                    string FFN = firstname + finaldate + firstext;
                    string SFN = secondname + finaldate + secondext;

                    #endregion

                    string firstPath = Server.MapPath("~/Content/" + FFN);
                    string secondPath = Server.MapPath("~/Content/" + SFN);

                    files.Get(0).SaveAs(firstPath);
                    files.Get(1).SaveAs(secondPath);

                    #region Read the data from the first Excel File
                    Excel.Application Fapplication = new Excel.Application();
                    Excel.Workbooks Fworkbooks = Fapplication.Workbooks;
                    Excel.Workbook Fworkbook = Fworkbooks.Open(firstPath);
                    Excel.Worksheet Fworksheet = (Excel.Worksheet)Fworkbook.ActiveSheet;
                    Excel.Range Frange = Fworksheet.UsedRange;

                    List<ExcelInfo> firstFileContent = new List<ExcelInfo>();
                    for (int row = 1; row <= Frange.Rows.Count; row++)
                    {
                        ExcelInfo ei = new ExcelInfo();
                        ei.periode = 1;
                        ei.journal = ((string)((Excel.Range)Frange.Cells[row, 1]).Text);
                        ei.compte = ((string)((Excel.Range)Frange.Cells[row, 2]).Text);

                        string date = (string)(((Excel.Range)Frange.Cells[row, 3]).Value2.ToString());
                        //DateTime myDate = DateTime.Parse(date, new CultureInfo("en-US", true));

                        //string sDate = (xlRange.Cells[4, 3] as Excel.Range).Value2.ToString();
                        double ddate = double.Parse(date);
                        var myDate = DateTime.FromOADate(ddate);
                        if (!(myDate > model.firstPeriodStart && myDate < model.firstPeriodEnd))
                        {
                            @ViewBag.firstPeriodError = "Cette date n'appartient pas à l'intervalle de la première période." + myDate.ToString("D");
                            return View("Input");
                        }
                        ei.dateEcriture = myDate;
                        ei.debit = Int32.Parse((string)((Excel.Range)Frange.Cells[row, 4]).Text);
                        ei.credit = Int32.Parse((string)((Excel.Range)Frange.Cells[row, 5]).Text);
                        firstFileContent.Add(ei);
                    }
                    Fworkbook.Close();
                    Marshal.ReleaseComObject(Fworkbook);
                    Marshal.ReleaseComObject(Fworksheet);
                    Marshal.ReleaseComObject(Frange);
                    Fapplication.Quit();
                    Fworkbook = null;
                    Fworksheet = null;
                    Fapplication = null;
                    #endregion

                    #region Read the data from the second Excel File
                    Excel.Application Sapplication = new Excel.Application();
                    Excel.Workbooks Sworkbooks = Sapplication.Workbooks;
                    Excel.Workbook Sworkbook = Sworkbooks.Open(secondPath);
                    Excel.Worksheet Sworksheet = (Excel.Worksheet)Sworkbook.ActiveSheet;
                    Excel.Range Srange = Sworksheet.UsedRange;

                    List<ExcelInfo> secondFileContent = new List<ExcelInfo>();
                    for (int row = 1; row <= Srange.Rows.Count; row++)
                    {
                        ExcelInfo ei = new ExcelInfo();
                        ei.periode = 2;
                        ei.journal = (string)((Excel.Range)Srange.Cells[row, 1]).Text;
                        ei.compte = ((string)((Excel.Range)Srange.Cells[row, 2]).Text);

                        string date = (string)(((Excel.Range)Srange.Cells[row, 3]).Value2.ToString());
                        //DateTime myDate = DateTime.Parse(date, new CultureInfo("en-US", true));

                        //string sDate = (xlRange.Cells[4, 3] as Excel.Range).Value2.ToString();
                        double ddate = double.Parse(date);
                        var myDate = DateTime.FromOADate(ddate);
                        if (!(myDate > model.secondPeriodStart && myDate < model.secondPeriodEnd))
                        {
                            @ViewBag.secondPeriodError = "Cette date n'appartient pas à l'intervalle de la deuxième période." + myDate.ToString("D");
                            return View("Input");
                        }
                        ei.dateEcriture = myDate;
                        ei.debit = Int32.Parse((string)((Excel.Range)Srange.Cells[row, 4]).Text);
                        ei.credit = Int32.Parse((string)((Excel.Range)Srange.Cells[row, 5]).Text);
                        secondFileContent.Add(ei);
                    }
                    Sworkbook.Close();
                    Marshal.ReleaseComObject(Sworkbook);
                    Marshal.ReleaseComObject(Sworksheet);
                    Marshal.ReleaseComObject(Srange);
                    Sapplication.Quit();
                    Sworkbook = null;
                    Sworksheet = null;
                    Sapplication = null;
                    #endregion

                    var firstFileContentSession = from a in firstFileContent
                                                  select a;
                    var secondFileContentSession = from a in secondFileContent
                                                   select a;

                    generalSettings ste = (generalSettings)Session["SteInformation"];
                    model.exercice = ste.exercice;
                    model.ownerId = ste.ownerId;
                    model.matricule = ste.matricule;
                    model.firstfile = firstPath;
                    model.secondfile = secondPath;
                    db.ExcelModelViews.Add(model);
                    db.SaveChanges();

                    Session["firstInputFile"] = firstFileContentSession;
                    Session["secondInputFile"] = secondFileContentSession;
                    Session["ExcelModelView"] = model;

                    #region delete old files

                    ExcelModelView emv = (from a in db.ExcelModelViews
                                          where a.exercice == ste.exercice &&
                                                a.matricule.Equals(ste.matricule) &&
                                                a.ownerId.Equals(ste.ownerId)

TASEF/TASEF/Views/Home/Delete.cshtml
@model TASEF.Models.generalSettings

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Confirmer la suppression!</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.nomEtPrenomRaisonSociale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomEtPrenomRaisonSociale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.activite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.activite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateDebutExercice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateDebutExercice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateClotureExercice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateClotureExercice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.actededepot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.actededepot)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.natureDepot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.natureDepot)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour", "Index")
        </div>
    }
</div>

TASEF/TASEF/Views/Home/Details.cshtml
@model TASEF.Models.generalSettings

@{
    ViewBag.Title = "Détails entreprise";
    string action = ViewBag.action;
    string controller = ViewBag.controller;
}

<h2>Entreprise</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt id="L">
            - @Html.DisplayNameFor(model => model.matricule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.matricule)
        </dd>

        <dt id="L">
            - @Html.DisplayNameFor(model => model.nomEtPrenomRaisonSociale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomEtPrenomRaisonSociale)
        </dd>
          <dt id="L">
           - @Html.DisplayNameFor(model => model.exercice)
        </dt>

        <dd >
            @Html.DisplayFor(model => model.exercice)
        </dd>

        <dt id="L">
            - @Html.DisplayNameFor(model => model.activite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.activite)
        </dd>

        <dt id="L">
            - @Html.DisplayNameFor(model => model.adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adresse)
        </dd>

        <dt id="L">
            - @Html.DisplayNameFor(model => model.dateDebutExercice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateDebutExercice)
        </dd>

        <dt id="L">
            - @Html.DisplayNameFor(model => model.dateClotureExercice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateClotureExercice)
        </dd>

        <dt id="L">
            - @Html.DisplayNameFor(model => model.actededepot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.actededepot)
        </dd>

        <dt id="L">
            - @Html.DisplayNameFor(model => model.natureDepot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.natureDepot)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { ownerId= Model.ownerId, matricule = Model.matricule, exercice = Model.exercice }, new { id="brownLink"}) |
    @Html.ActionLink("Retour", action,controller,null, new { id = "brownLink" })
</p>

TASEF/TASEF/Views/Home/Edit.cshtml
@model TASEF.Models.generalSettings

@{
    ViewBag.Title = "Modifier";
}

<h2>Modifier les informations de l'entreprise</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ownerId)
        <div class="form-group">
            @Html.LabelFor(model => model.exercice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.exercice, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.exercice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.matricule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.matricule, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.matricule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nomEtPrenomRaisonSociale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomEtPrenomRaisonSociale, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomEtPrenomRaisonSociale, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.activite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.activite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.activite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adresse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adresse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adresse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateDebutExercice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateDebutExercice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateDebutExercice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateClotureExercice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateClotureExercice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateClotureExercice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.actededepot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("actededepot", new List<SelectListItem>
                     { new SelectListItem { Text = "Spontané", Value = "Spontané", Selected=true},
                       new SelectListItem { Text = "Rectification", Value = "Rectification"},
                       new SelectListItem { Text = "Régularisation", Value = "Régularisation"}
                       }, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.actededepot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.natureDepot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("naturedepot", new List<SelectListItem>
                                 { new SelectListItem { Text = "Définitif", Value = "Définitif", Selected=true},
                                   new SelectListItem { Text = "Provisoire", Value = "Provisoire"},
                                   }, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.natureDepot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TASEF/TASEF/Views/Home/Index.cshtml
@model IEnumerable<TASEF.Models.generalSettings>
@using TASEF.Models

@{
    ViewBag.Title = "Entreprises";
    generalSettings gs = (generalSettings)Session["SteInformation"];
    string matricule = "";
    int exercice = 0;
    string value = "class=dd";
    string message = "Selected ";
    if (gs != null)
    {
        matricule = gs.matricule;
        exercice = gs.exercice;
    }

}

<h2>Sélectionner une entreprise !</h2>
<p>ou @Html.ActionLink("Ajouter une nouvelle entreprise", "index", "Excel",null,new { @class= "btn btn-default" }) </p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.matricule)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nomEtPrenomRaisonSociale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.exercice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateDebutExercice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateClotureExercice)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr @{if ((matricule.Equals(item.matricule)) && (exercice == item.exercice)) { @value  }}>
        <td>
            @Html.DisplayFor(modelItem => item.matricule)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nomEtPrenomRaisonSociale)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.exercice)
        </td>
        <td>
            @item.dateDebutExercice.ToString("D")
        </td>
        <td>
            @item.dateClotureExercice.ToString("D")
        </td>
        <td>
            @{if ((matricule.Equals(item.matricule)) && (exercice == item.exercice))
                { @message }
            else
            {@Html.ActionLink("Selectionner", "Select", new { ownerId = item.ownerId, matricule = item.matricule, exercice = item.exercice }) }
            } |
            @Html.ActionLink("Détails", "Details", new { ownerId = item.ownerId, matricule = item.matricule, exercice = item.exercice, test = 1 }) |
            @Html.ActionLink("Supprimer", "Delete", new { ownerId = item.ownerId, matricule = item.matricule, exercice = item.exercice })

        </td>
    </tr>
    }

</table>

TASEF/TASEF/Views/Home/try2.cshtml
@model IEnumerable<TASEF.Models.generalSettings>
@using TASEF.Models
@section style
{
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Table/vendor/animate/animate.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Table/vendor/select2/select2.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Table/vendor/perfect-scrollbar/perfect-scrollbar.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Table/css/util.css">
<link rel="stylesheet" type="text/css" href="~/Content/Table/css/main.css">
<!--===============================================================================================-->
}
@{
    ViewBag.Title = "Index";
    generalSettings gs = (generalSettings)Session["SteInformation"];
    string matricule = "";
    int exercice = 0;
    string value = "class=dd";
    string message = "Selected ";
    if (gs != null)
    {
        matricule = gs.matricule;
        exercice = gs.exercice;
    }

}

<h2>Select which company you want to work with </h2>
<p>Or @Html.ActionLink("Add a new one", "index", "Excel") </p>

<div class="limiter">
    <div class="container-table100">
        <div class="wrap-table100">
            <div class="table">

                <div class="row header">
                    <div class="cell">
                        @Html.DisplayNameFor(model => model.matricule)
                    </div>
                    <div class="cell">
                        @Html.DisplayNameFor(model => model.exercice)
                    </div>
                    <div class="cell">
                        @Html.DisplayNameFor(model => model.dateDebutExercice)
                    </div>
                    <div class="cell">
                        @Html.DisplayNameFor(model => model.dateClotureExercice)
                    </div>
                    <div class="cell">
                    </div>
                </div>

                @foreach (var item in Model)
                {
                    <div class="row" @{if ((matricule.Equals(item.matricule)) && (exercice == item.exercice)) { @value  }}>
                        <div class="cell" data-title="matricule">
                            @Html.DisplayFor(modelItem => item.matricule)
                        </div>
                        <div class="cell" data-title="exercice">
                            @Html.DisplayFor(modelItem => item.exercice)
                        </div>
                        <div class="cell" data-title="date Debut Exercice">
                            @item.dateDebutExercice.ToString("D")
                        </div>
                        <div class="cell" data-title="date Cloture Exercice">
                            @item.dateClotureExercice.ToString("D")
                        </div>
                        <div class="cell" data-title="links">
                            @{if ((matricule.Equals(item.matricule)) && (exercice == item.exercice))
                                { @message }
                            else
                            {@Html.ActionLink("Select", "Select", new { ownerId = item.ownerId, matricule = item.matricule, exercice = item.exercice }) }
                            } |
                            @Html.ActionLink("Details", "Details", new { ownerId = item.ownerId, matricule = item.matricule, exercice = item.exercice, test = 1 }) |
                            @Html.ActionLink("Delete", "Delete", new { ownerId = item.ownerId, matricule = item.matricule, exercice = item.exercice })

                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

@section script {
<!--===============================================================================================-->
<script src="~/Content/Table/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="~/Content/Table/vendor/bootstrap/js/popper.js"></script>
<script src="~/Content/Table/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="~/Content/Table/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="~/Content/Table/js/main.js"></script>
}