TASEF/TASEF/Controllers/PassifParametersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using TASEF.Infrastructure;
using TASEF.Migrations.OtherDbContext;
using TASEF.Models;

namespace TASEF.Controllers
{
    public class PassifParametersController : Controller
    {


        private ExcelProjectContext db = new ExcelProjectContext();

        // GET: Parameters
        [Authorize]
        public ActionResult Index()
        {
            if (Session["SteInformation"] == null)
            {
                ViewBag.Error = "Vous devez d'abord choisir une entreprise ! <a href=\"/Home/Index\"> Tous les entreprises </a>";
                return View("FileError");
            }
            else if (Session["firstInputFile"] == null || Session["secondInputFile"] == null || Session["ExcelModelView"] == null)
            {
                ViewBag.Error = "Vous devez d'abord importer les fichiers  !  <a href=\"/Excel/Input\"> Importer </a>";
                return View("FileError");
            }

            generalSettings gs = (generalSettings)Session["SteInformation"];

            var ParamSetting = from ps in db.ParametersSetting
                               where ps.ownerId.Equals(gs.ownerId) && ps.matricule.Equals(gs.matricule) && ps.exercice == gs.exercice
                               select ps;
            ParametersSetting paramPassif = ParamSetting.FirstOrDefault();

            if (!paramPassif.hasParamPassif)
                return View("ParamSetting");
            else
            {
                

                IEnumerable<ExcelInfo> firstInputFile = (IEnumerable<ExcelInfo>)Session["firstInputFile"];
                IEnumerable<ExcelInfo> secondInputFile = (IEnumerable<ExcelInfo>)Session["secondInputFile"];

                IEnumerable<ExcelInfo> InputFile = firstInputFile.Concat(secondInputFile);

                //calculate the values foreach parameter
                int exercice = gs.exercice;
                string matricule = gs.matricule;
                string ownerId = gs.ownerId;

                var af = from a in db.PassifModel
                         where a.exercice == exercice && a.matricule.Equals(matricule) && a.ownerId.Equals(ownerId)
                         select a;

                var databaseFormulaList = from fl in db.PassifFormula
                                          where fl.exercice == exercice && fl.matricule.Equals(matricule) && fl.ownerId.Equals(ownerId)
                                          select fl;


                //there are no Passif parameters for that company so we need to create them
                if (!af.Any())
                {
                    List<PassifParamModel> PassifParamList = new List<PassifParamModel>
            {
                new PassifParamModel(){ code="0001" , libelle ="Capitaux propres" , type="Formula",state="Stable",priority=1},
                new PassifParamModel(){ code="0002" , libelle ="Capital social" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0003" , libelle ="Réserves" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0004" , libelle ="Autres capitaux propres" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0005" , libelle ="Résultats reportés" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0006" , libelle ="Capitaux propres avant résultat de l'exercice" , type="Formula",state="Stable",priority=0},
                new PassifParamModel(){ code="0007" , libelle ="Résultat de l'exercice" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0008" , libelle ="Total Passifs" , type="Formula",state="Stable",priority=2},
                new PassifParamModel(){ code="0009" , libelle ="Passifs non courants" , type="Formula",state="Stable",priority=1},
                new PassifParamModel(){ code="0010" , libelle ="Emprunts" , type="Formula",state="Stable",priority=0},
                new PassifParamModel(){ code="0011" , libelle ="Emprunts obligataires (assortis de sûretés)" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0012" , libelle ="Empts auprès d'étab.Fin. (assortis de sûretés)" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0013" , libelle ="Empts auprès d'étab.Fin. (assorti de sûretés)" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0014" , libelle ="Empts et dettes assorties de condit. particulières" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0015" , libelle ="Emprunts non assortis de sûretés" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0016" , libelle ="Dettes rattachées à des participations" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0017" , libelle ="Dépôts  et  cautionnements reçus" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0018" , libelle ="Autres emprunts et dettes" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0019" , libelle ="Autres Passifs Financiers" , type="Formula",state="Stable",priority=0},
                new PassifParamModel(){ code="0020" , libelle ="Écarts de conversion" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0021" , libelle ="Autres passifs financiers" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0022" , libelle ="Provisions" , type="Formula",state="Stable",priority=0},
                new PassifParamModel(){ code="0023" , libelle ="Provisions pour risques" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0024" , libelle ="Prov.pour charges à répartir/plusieurs exercices" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0025" , libelle ="Prov.pour retraites et obligations similaires" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0026" , libelle ="Provisions d'origine réglementaire" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0027" , libelle ="Provisions pour impôts" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0028" , libelle ="Prov.pour renouvellement des immobilisations" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0029" , libelle ="Provisions pour amortissement" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0030" , libelle ="Autres provisions pour charges" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0031" , libelle ="Passifs courants" , type="Formula",state="Stable",priority=1},
                new PassifParamModel(){ code="0032" , libelle ="Fournisseurs et Comptes Rattachés" , type="Formula",state="Stable",priority=0},
                new PassifParamModel(){ code="0033" , libelle ="Fournisseurs d'exploitation" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0034" , libelle ="Fournisseurs d'exploitation - effets à payer" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0035" , libelle ="Fournisseurs d'immobilisations" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0036" , libelle ="Fournisseurs d'immobilisations - effets à payer" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0037" , libelle ="Fournisseurs - factures non parvenues" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0038" , libelle ="Autres passifs courants" , type="Formula",state="Stable",priority=0},
                new PassifParamModel(){ code="0039" , libelle ="Clients créditeurs" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0040" , libelle ="Sociétés du groupe  et  associés" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0041" , libelle ="État et collectivités publiques" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0042" , libelle ="Sociétés du groupe  et  associés" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0043" , libelle ="Débiteurs divers et Créditeurs divers" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0044" , libelle ="Comptes transitoires ou d'attente" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0045" , libelle ="Comptes de régularisation" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0046" , libelle ="Provisions courantes pour risques et charges" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0047" , libelle ="Concours Bancaires et Autres Passifs Financiers" , type="Formula",state="Stable",priority=0},
                new PassifParamModel(){ code="0048" , libelle ="Emprunts et autres dettes financières courants" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0049" , libelle ="Emprunts échus et impayés" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0050" , libelle ="Intérêts courus" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0051" , libelle ="Banques, établissements financiers et assimilés" , type="Calculated",state="Stable"},
                new PassifParamModel(){ code="0052" , libelle ="Autres Postes des Capitaux Propres et Passifs du Bilan" , type="Calculated",state="Stable"},

TASEF/TASEF/Views/PassifParameters/Create.cshtml
@model TASEF.Models.PassifFormula

@{
    ViewBag.Title = "Ajouter formule";
}

<h2>Ajouter formule</h2>
@{
    if (@ViewBag.listFormula != null)
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.codeDonnee)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.nomCompte)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.typeFormule)
                </th>
                <th id="smallParameterLinks"></th>
            </tr>

            @foreach (var item in @ViewBag.listFormula)
            {
                <tr>
                    <td>
                        @item.codeDonnee
                    </td>
                    <td>
                        @item.nomCompte
                    </td>
                    <td>
                        @{ if (@item.typeFormule.Equals("Solde"))
                            {
                                @("Solde")
                            }
                            else if (@item.typeFormule.Equals("MvtDebit"))
                            { @("Mouvement Débiteur") }
                        else if (@item.typeFormule.Equals("MvtCredit"))
                        { @("Mouvement Créditeur") }
                    else if (@item.typeFormule.Equals("SoldeSiD"))
                    { @("Solde Si Débiteur") }
                else if (@item.typeFormule.Equals("SoldeSiC"))
                { @("Solde Si Créditeur") }
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Modifier", "EditFormula", new { id = item.Id }) |
                        @Html.ActionLink("Supprimer", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    } }

<button id="show" class="btn btn-default">Ajouter compte</button>
@using (Html.BeginForm("Create", "PassifParameters", FormMethod.Post, new { @style = "display:none", id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Formule</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.codeParam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codeParam, new { htmlAttributes = new { @class = "form-control", Value = Model.codeParam, type = "hidden" } })
                @Html.EditorFor(model => model.codeParam, new { htmlAttributes = new { @class = "form-control", Value = Model.codeParam, @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.codeParam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.codeDonnee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codeDonnee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codeDonnee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nomCompte, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomCompte, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomCompte, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.typeFormule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("typeFormule", new List<SelectListItem>
                                 { new SelectListItem { Text = "Solde", Value = "Solde", Selected=true},
                                   new SelectListItem { Text = "Mouvement Débiteur", Value = "MvtDebit"},
                                   new SelectListItem { Text = "Mouvement Créditeur", Value = "MvtCredit"},
                                   new SelectListItem { Text = "Solde Si Débiteur", Value = "SoldeSiD"},
                                   new SelectListItem { Text = "Solde Si Créditeur", Value = "SoldeSiC"}
                                   }, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.typeFormule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index", null, new { id = "brownLink" })
</div>

@section Scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#hide").click(function () {
                $("form").hide();
            });
            $("#show").click(function () {
                $("form").show();
            });
        });
    </script>

}

TASEF/TASEF/Views/PassifParameters/Delete.cshtml
@model TASEF.Models.PassifFormula

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Confirmer la suppression!</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.codeParam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codeParam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.codeDonnee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codeDonnee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nomCompte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomCompte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typeFormule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeFormule)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour", "Index", null, new { id = "brownLink" })
        </div>
    }
</div>

TASEF/TASEF/Views/PassifParameters/EditFormula.cshtml
@model TASEF.Models.PassifFormula

@{
    ViewBag.Title = "Modifier formule";
}

<h2>Modification de formule</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Formule</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    @Html.HiddenFor(model => model.exercice)

    @Html.HiddenFor(model => model.matricule)
    @Html.HiddenFor(model => model.ownerId)

    <div class="form-group">
        @Html.LabelFor(model => model.codeParam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.codeParam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.codeParam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.codeDonnee, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.codeDonnee, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.codeDonnee, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nomCompte, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nomCompte, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nomCompte, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.typeFormule, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("typeFormule", new List<SelectListItem>
                            { new SelectListItem { Text = "Solde", Value = "Solde", Selected=true},
                              new SelectListItem { Text = "Mouvement Débiteur", Value = "MvtDebit"},
                              new SelectListItem { Text = "Mouvement Créditeur", Value = "MvtCredit"},
                              new SelectListItem { Text = "Solde Si Débiteur", Value = "SoldeSiD"},
                              new SelectListItem { Text = "Solde Si Créditeur", Value = "SoldeSiC"}
                              }, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.typeFormule, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Enregistrer" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour", "Index", null, new { id = "brownLink" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TASEF/TASEF/Views/PassifParameters/EditParam.cshtml
@model TASEF.Models.PassifParamModel

@{
    ViewBag.Title = "Modifier paramétres";
}

<h2>Modification du paramétre</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Paramétre</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.code)

    @Html.HiddenFor(model => model.exercice)

    @Html.HiddenFor(model => model.matricule)
    @Html.HiddenFor(model => model.ownerId)

    @Html.HiddenFor(model => model.libelle)

    @Html.HiddenFor(model => model.type)


    <div class="form-group">
        @Html.LabelFor(model => model.netN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.netN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.netN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.netN1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.netN1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.netN1, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Enregistrer" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour", "Index", null, new { id = "brownLink" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TASEF/TASEF/Views/PassifParameters/GenerateFiles.cshtml
@{
    ViewBag.Title = "Fichiers";
}

<h2>Génération des fichiers</h2>
<div id="wrapper">
    <div id="centerDiv">
        @Html.ActionLink("Générer le fichier .pdf", "PrintPassifsAsPdf", "PassifParameters", null, new { @class = "btn btn-default" })

        @Html.ActionLink("Générer le fichier .xml", "PrintPassifsAsXml", "PassifParameters", null, new { @class = "btn btn-default", id = "buttonMargin" })
    </div>
</div>

TASEF/TASEF/Views/PassifParameters/GenerateNoteFiles.cshtml
@{
    ViewBag.Title = "Notes";
}

<h2>Génération des notes</h2>
<div id="wrapper">
    <div id="centerDiv">
        @Html.ActionLink("Générer le fichier .pdf", "PrintPassifNotesAsPdf", "PassifParameters", null, new { @class = "btn btn-default" })
    </div>
</div>

TASEF/TASEF/Views/PassifParameters/Index.cshtml
@model IEnumerable<TASEF.Models.PassifParamModel>
@using TASEF.Models;
@{
    ViewBag.Title = "Passif";
    generalSettings gs = (generalSettings)Session["SteInformation"];
    string value = "class=dd";
}

<div>
    <h2>Passif</h2>


    <table id="infoTable">
        <tr>
            <td>
                <label>Entreprise sélectionnée :</label> @gs.nomEtPrenomRaisonSociale &emsp;&emsp;
            </td>
            <td>
                <label>Exercice :</label>  @gs.exercice &emsp;&emsp;
            </td>
            <td>
                <label>Date début exercice :</label>  @gs.dateDebutExercice.ToShortDateString() &emsp;&emsp;
            </td>
            <td>
                <label>Date clotûre exercice :</label> @gs.dateClotureExercice.ToShortDateString() &emsp;&emsp;
            </td>
        </tr>
    </table>
</div>
<p>
    @Html.ActionLink("Recalculer", "Recalculate", null, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.libelle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.netN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.netN1)
        </th>
        <th id="parameterLinks"></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr  @{if (item.type.Equals("Formula")) { @value  }}>
            <td>
                @Html.DisplayFor(modelItem => item.code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.libelle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.netN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.netN1)
            </td>
            <td>
                @{
                    if (item.type.Equals("Calculated"))
                    {
                        @Html.ActionLink("Ajouter formule", "Create", new { id = item.code })
                    }
                    else
                    {
                        @Html.ActionLink("Détails", "Show", new { id = item.code })
                    }
                } |
                @Html.ActionLink("Modifier les valeurs", "EditParam", new { ownerId=item.ownerId,code = item.code,exercice = item.exercice,matricule = item.matricule })
            </td>
        </tr>
    }

</table>

TASEF/TASEF/Views/PassifParameters/PassifNotesAsPdf.cshtml
@model IEnumerable<TASEF.Models.ActifParamModel>
@using TASEF.Models;
@{
    ViewBag.Title = "Notes - Passifs";
    Layout = "~/Views/Shared/_pdfLayout.cshtml";
    string value = "class=dd";
    generalSettings gs = (generalSettings)Session["SteInformation"];
    string exercice = gs.dateClotureExercice.ToString("dd/MM/yyyy");
    string exercice1 = gs.dateClotureExercice.AddYears(-1).ToString("dd/MM/yyyy");
}

<table class="table">
    <tr>
        <th>
            Note
        </th>
        <th>
           
        </th>
        <th>
            
        </th>
        <th>
            @exercice
        </th>
        <th>
            @exercice1
        </th>
        <th>
            Différence
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.type.Equals("Calculated"))
        {
        <tr>
            <td>
                @item.code
            </td>
            <td style="color:red">
                @Html.DisplayFor(modelItem => item.libelle)
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
            <td></td>
        </tr>

            IEnumerable<PassifFormula> af = ViewBag.listFormula;
            IEnumerable<PassifFormula> specificaf = af.Where(F => F.codeParam.Equals(item.code));

            foreach (PassifFormula saf in specificaf)
            {
        <tr>
            <td></td>
            <td id="code">@saf.codeDonnee</td>
            <td >@saf.nomCompte</td>
            @{
                float first = 0;
                float second = 0;
                float diff;
                foreach (ExcelInfo aaf in ViewBag.firstFile)
                {
                    if (aaf.compte.StartsWith(saf.codeDonnee))
                    {
                        first += aaf.debit - aaf.credit;
                    }
                }
                foreach (ExcelInfo aaaf in ViewBag.secondFile)
                {

                    if (aaaf.compte.StartsWith(saf.codeDonnee))
                    {
                        second += aaaf.debit - aaaf.credit;
                    }
                }
            }
            <td>@first</td>
            <td>@second</td>
            @{diff = first - second;}
            <td>@diff</td>
        </tr>
            }
        }

    }

</table>

TASEF/TASEF/Views/PassifParameters/PassifsAsPdf.cshtml
@model IEnumerable<TASEF.Models.PassifParamModel>

@{
    ViewBag.Title = "Passifs";
    Layout = "~/Views/Shared/_pdfLayout.cshtml";
    string value = "class=dd";
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.libelle)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.netN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.netN1)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr @{if (item.type.Equals("Formula")) { @value  }}>
            <td>
                @Html.DisplayFor(modelItem => item.code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.libelle)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.netN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.netN1)
            </td>
        </tr>
    }

</table>

TASEF/TASEF/Views/PassifParameters/Show.cshtml
@model IEnumerable<TASEF.Models.PassifParamModel>

@{
    ViewBag.Title = "Détails paramétre";
    List<string> minus = (List<string>)ViewBag.minus;
    string value1 = "class=dd";
    string value2 = "class=gg";
}

<h2>Liste des paramétres</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.libelle)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.netN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.netN1)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr @{ if (minus.Contains(item.code)) { @value1 } else { @value2 }}>
        <td>
            @Html.DisplayFor(modelItem => item.code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.libelle)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.netN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.netN1)
        </td>
    </tr>
}

</table>